# https://taskfile.dev

version: "3"

tasks:
  clippy:
    cmds:
      - cargo clippy --fix
    desc: Run clippy

  build-release:
    cmds:
      - cargo build --release
    desc: Builds release version of the app

  create-manifest:
    cmds:
      - cargo run --release -- --cwd "{{.USER_WORKING_DIR}}" --alias mgen
    desc: Runs create manifest for current crate.
