# https://taskfile.dev

version: "3"

tasks:
  clippy:
    cmds:
      - cargo clippy --fix
    silent: true

  release:
    cmds:
      - cargo build --release

  manifest:
    cmds:
      - cargo run --release -- --cwd "{{.USER_WORKING_DIR}}" --alias mgen
