# https://taskfile.dev

version: "3"

tasks:
  clippy-fix:
    cmds:
      - cargo clippy --fix
    desc: Run clippy

  build-release:
    cmds:
      - cargo build --release
    desc: Builds release version of the app

  create-manifest:
    cmds:
      - cargo run --release -- --cwd "{{.USER_WORKING_DIR}}" --alias mgen
    desc: Runs create manifest for current crate.

  release-with-manifest:
    aliases:
      - "rwm"
    cmds:
      - task: build-release
      - task: create-manifest
    desc: Calls release build, then creates manifest for this build

  scoop-install:
    cmds:
      - scoop install "$HOME\scoop\buckets\local\pseudo_manifest"
    desc: Installs the app with Scoop
